apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: flink-operator
deploy:
  helm:
    releases:
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        namespace: cert-manager
        createNamespace: true
        version: v1.16.1
        setValues:
          installCRDs: true
      - name: flink-kubernetes-operator
        repo: https://archive.apache.org/dist/flink/flink-kubernetes-operator-1.10.0
        remoteChart: flink-kubernetes-operator
        namespace: default # flink-operator
        createNamespace: true
        wait: true
        setValues:
          webhook.create: false