apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: word-count
build:
  artifacts:
    - image: flink-beam-example
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - word-count-example.yaml
    - rbac.yaml
deploy:
  kubectl: { }
